config/routes.rb
Magicaccounts::Application.routes.draw do  
  controller :reports do
    get 'reports' => :index
    get "spend_by_category" => "reports#spend_by_category"
    get "spend_by_account" => "reports#spend_by_account"
    get "spend_by_user" => "reports#spend_by_user"
    get "transaction_count_by_category" => "reports#transaction_count_by_category"
    get "transaction_count_by_account" => "reports#transaction_count_by_account"
    get "avg_spend_by_category" => "reports#avg_spend_by_category"
    get "avg_spend_by_account" => "reports#avg_spend_by_account"
  end

  resources :comments do
    collection do
      get :recent_activities
    end
  end

  root :to => 'users#dashboard'
  match 'groups/:code/adduser' => 'groups#adduser'
  match 'transactions/new/:groupid' => 'transactions#new'
  match 'profile' => "users#dashboard"
  match 'groups/sendinvites' => 'groups#sendinvites'

  controller :sessions do
    get   'login' => :new
    post  'login' => :create
    get   'logout' => :destroy
  end

  resources :groups

  resources :transactions do
    collection do
      get :get_group_balance
      get :autocomplete_category_tags
      get :settle_up
    end
  end

  resources :users do
    collection do
      get :autocomplete_friends
    end

    member do
      get :dashboard
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users, :uniq => true
  has_many :transactions, :dependent => :destroy
  has_many :comments
  belongs_to :user
  
  module GROUPSTATUS
    ENABLED = "Enabled"
    DISABLED = "Disabled"
    ALL = [ENABLED, DISABLED]  
  end

  validates :name, 
            :uniqueness => {:scope => :user_id, :message => 'Group name already taken by you. Choose another name'},
            :presence   => {:message => 'Group name cannot be blank'},
            :length     => {:in => 4..32, :message => "Name should be between 4 and 32 characters"},
            :format     => {:with => /^[a-zA-Z0-9]+[ a-zA-Z0-9_'-]*[a-zA-Z0-9]+$/, :message => 'Name must start and end with an alphabet or digit and can contain only alphanumeric, spaces, hyphens, apostrophes and underscores'}

  validates :status,
            :inclusion => { :in => GROUPSTATUS::ALL, :message => "please select Enabled or Disabled" }

  validates :user_id,
            :presence => {:message => 'user_id is mandatory'}#,
            #:inclusion => { :in => User.find(:all).map {|user| user.id}, :message => "user include is mandatory "}

  validates :code,
            :presence => {:message => "group code is mandatory"},
            :length   => {:maximum => 50 }

  def self.get_user_owned_groups(current_user)
    Group.find_all_by_user_id(current_user)
  end

  def self.get_groups_for_current_user(current_user)
      Group.where(" id IN (SELECT DISTINCT group_id FROM groups_users where user_id = ?)",current_user)
  end

  def user_attributes=(user_attributes)
    self.users = []
    user_attributes.each do |key, attributes|
      user = User.find_by_email(attributes[:email])
      unless user
        user = User.new(attributes)
        user.password = (0...8).map{ ('a'..'z').to_a[rand(26)] }.join
        user.password_confirmation = user.password
        user.save!
        MagicMailer.group_invite(self,attributes[:email]).deliver
      end
      self.users << user
    end
  end

 def self.autocomplete_results(named_query,user,page_limit = 10,page = 1)
      results = user.contacts.paginate(:page => page, :per_page => page_limit,:conditions => ['email LIKE ?', "%#{named_query}%"])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    # Get all user's groups
    @groups = current_user.user_groups.page(params[:page]).per_page(10)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find_by_id(params[:id])
      session[:original_uri] = request.url
    @balances = Transaction.user_balance(@group).collect do |entry| 
      { 
        :user_id => entry.user_id, 
        :balance => entry.balance.abs.to_s, 
        :transaction_count => entry.transactions,
        :display_class => entry.balance > 0 ? "positive" : "negative"
      }
    end
    @user_balance = @balances.select{|x| x[:user_id] == current_user.id}.first
    respond_to do |format|
      if true
        format.html # show.html.erb
        format.js
        format.json { render json: @group }
      else
        flash[:error] = "Group was not found"
        format.html { redirect_to action: "index" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new    

    @group.users << (current_user)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find_by_id(params[:id])

    respond_to do |format|
      if Group.find_all_by_user_id(current_user).include?(@group)
        format.html # edit.html.erb
        format.json { render json: @group }
      else
        flash[:error] = "Group was not found"
        format.html { redirect_to action: "index" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])
    respond_to do |format|
      if @group.save          
        format.html { redirect_to groups_path, notice: "Group '#{@group.name}' was successfully created." }
        format.json { render json: @group, status: :created, location: @group }
      else
        flash[:error] = "Sorry, your group was not created. #{@group.errors.full_messages.to_sentence}"
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find_by_id(params[:id])
    
    respond_to do |format|
      if Group.find_all_by_user_id(current_user).include?(@group)
        if @group.update_attributes(params[:group])
          format.html { redirect_to groups_path, notice: "Group '#{@group.name}' was successfully updated." }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @group.errors, status: :unprocessable_entity }
        end
      else
        flash[:error] = "Group was not found"
        format.html { redirect_to action: "index" }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find_by_id(params[:id])
    if Group.find_all_by_user_id(current_user).include?(@group)
      flash[:notice] = "Group #{@group.name} was successfully removed"
      @group.destroy
    else
      flash[:error] = "Group was not found"      
    end
    
    respond_to do |format|      
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end

  def adduser
    @group = Group.find_by_code(params[:code])    
    respond_to do |format|
      if @group
        if @group.users.include?(current_user)
            format.html { redirect_to profile_url, notice: "You are already part of '#{@group.name}'" }
            format.json { render json: @group.errors, status: :unprocessable_entity }
        else
          @group.users << (current_user)
          if @group.save
            format.html { redirect_to profile_url, notice: "You have been added to '#{@group.name}'" }
            format.json { head :ok }
          else
            flash[:error] = "Cannot complete your request. Unknown Error"
            format.html { redirect_to groups_url }
            format.json { render json: @group.errors, status: :unprocessable_entity }
          end
        end
      else
        flash[:error] = "Cannot complete your request. Attempt to access an Invalid page"
        format.html { redirect_to groups_url }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def sendinvites
    debugger
    @toemail = params[:emailids]
    @group = Group.find_by_id(params[:groupid].to_i)
    error_msg = []
    if @toemail.present?
      @toemail.split(',').each do |email|
      begin
        if email =~ /[0-9]+/ 
          email = Contact.where(:id => email.to_i).first.try(:email) || email
        end
        if email && email != "" && email =~ /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/
          if handle_add_group_user(email)
            MagicMailer.group_invite(@group,email).deliver
          else
            error_msg << email
          end
        else
          error_msg << email
        end
      rescue Exception
        flash.now[:error] = "Error sending invites"
      end
      end
    else
      error_msg << "Enter atleast one email"
    end

      if error_msg.empty?
        flash[:notice] = "Invites sent successfully"
      else
        flash[:error] = "Invitation(s) were not sent for " + error_msg.join(',')
      end
    respond_to do |format|
      format.html { redirect_to session[:original_uri] + "#profil"}
      format.js { redirect_to session[:original_uri] + "#profil"}
    end
  end

  def handle_add_group_user(email)
    user = User.find_by_email(email)
    if user 
      if @group.users.include?(user)
        return user.invite_status != "registered"
      else
        @group.users << user
        return true
      end
    else
      user = User.new(:name => email.split('@').first, :email => email)
      user.save(:validate => false)
      @group.users << user
      return true
    end
  end

  def autocomplete
    @entries = Group.autocomplete_results(params[:term],current_user,params[:page_limit], params[:page])
    @entries = @entries.collect{|e| {id: e.id || params[:term], avatar: Digest::MD5::hexdigest(e.email) ,text: e.email || params[:term]}}
    render :inline => @entries.to_json
  end

  def close_popover
    Group.find_by_user_id(current_user.id).update_attribute(:popover, false)
    render :nothing => true
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def get_owner_member_details(user, group)
    if group.user == user
      return "Owner", "success"
    else
      return "Member", "default"
    end
  end

	def get_activity_group(group)
	  @activitytran = Comment.where(["commentable_type = 'Transaction' AND commentable_id IN (?)", Transaction.get_user_transactions(current_user).collect(&:id)]).order("created_at DESC")
	  @activitytran.select{ |x| x.group_id == group.id}
	end
end

app/views/groups/_balance_entry.html.erb
<tr>
  <% user = User.find(balance_options[:user_id]) %>
  <td class="text-left col-xs-3">
    <%= render_user_image(user, 
      :size => 42, 
      :class_name => "img-circle mg-balance-user mg-tooltip").html_safe %>
  </td>
  <td class="text-center col-xs-6">
    <span class="badge balance <%= balance_options[:display_class] %>"><h5><%= balance_options[:balance] %></h5></span>
  </td>
  <td class="text-right col-xs-3">
    <span class="badge"><h5><%= balance_options[:transaction_count] %></h5></span>
  </td>
</tr>

app/views/groups/_form.html.erb
<div class="well">
  <fieldset>
    <%= f.hidden_field  :user_id, :value => current_user.id %>
    <%= f.hidden_field  :code, :value => Digest::SHA1.hexdigest(Time.now.to_s + rand.to_s) %>
    <%= f.hidden_field  :status, :value => Group::GROUPSTATUS::ENABLED %>
    <div class="form-group">
      <label for="inputEmail" class="col-xs-2 control-label">Name</label>
      <div class="col-xs-10">
        <%= f.text_field :name, :class => 'text_field form-control', :placeholder => "Group Name" %>
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword" class="col-xs-2 control-label">Users</label>
      <div class="col-xs-10">
        <div id="mg-group-users">
          <%= render :partial => "group_user", :collection => f.object.users %>
        </div>
        <div class="clearfix mg-add-group-user">
          <div class="col-xs-11 remove-left-gutter">
            &nbsp;
          </div>
          <%= link_to(new_user_path, :remote => true) do %>
            <div class="col-xs-1 remove-left-gutter remove-right-gutter text-danger">
              <button type="button" class="btn btn-success btn add-remove-users pull-right" onclick="">
                <i class="icon-plus-sign"></i>
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="col-xs-2">
        &nbsp;
      </div>
      <div class="col-xs-10">
        <%= link_to "Cancel", groups_path, :class=>"btn btn-default" %>
        <button type="submit" class="btn btn-primary">Submit</button> 
      </div>
    </div>
  </fieldset>
</div>

app/views/groups/_group_balance.html.erb
<div class = "text-center">
	<legend >Group Balance</legend>
	<% if @user_balance.nil? %> 
<p> Sorry, there are no transactions for this group </p>
<% else %>
	<div class="text-<%= @user_balance[:balance] == "0.0" ? "muted" : @user_balance[:display_class] == "negative" ? "danger" : "success" %>">
	<h5> <%= @user_balance[:balance] == "0.0" ? "Settled Up" : @user_balance[:display_class] == "negative" ? "You pay" : "You get" %></h5></div>
	<span class="badge balance <%= @user_balance[:balance] == "0.0" ? "muted" : @user_balance[:display_class] %>">
	<%= @user_balance[:balance] %>
	</span>
	<% end %>
	<legend >Recent Activity</legend>
	<% if get_activity_group(@group).empty? %>
		<p>There is no activity for this section<p></div>
	<%else%>
	<% activity_show_count = 0 %>
		<% get_activity_group(@group).each do |act| %>
		<% activity_show_count += 1 %>
			<% if activity_show_count < 4 %>
				<% activity_transaction = Transaction.find_by_id(act.commentable_id) %>
				<% if activity_transaction.present? %>
					<div class="list-group">
					<a href="<%= transaction_path(activity_transaction) %>" class="list-group-item">
					<h5 class="list-group-item-heading">
					<%= raw(render_user_image(act.user, 
					:size => 16, :class_name => "img-circle",:data_placement => "left") + render_activity(act)) %> </h5>
					<p class="list-group-item-text">
					<small>
					<%= activity_transaction.remarks %>
					</small>
					</p>
					</a>
					</div>
				<% end %>	
			<% end %>
		<% end%>
		<% if activity_show_count > 3 %>
			<%= link_to "More...",recent_activities_comments_path, :class => "pull-right" %>
		<% end %>
	<% end%>
<script type="text/javascript">
  jQuery('.img-circle').tooltip();
</script>

app/views/groups/_group_entry.html.erb
<tr class="mg-group-entry">
  <td class="text-center">
    <span class="icon-stack icon-2x">
      <i class="icon-sign-blank icon-stack-base"></i>
      <i class="icon-sitemap icon-light icon-child"></i>
    </span>
  </td>
  <td>   
    <div class="mg-group-name col-sm-12 remove-left-gutter remove-right-gutter">
      <%= link_to(group_path(entry), :class=>"text-primary") do %>
        <h5><b><%= entry.name %></b></h5>
      <% end %>
    </div>
    <% if can?(:invite_friends,entry) %>
    <%= link_to edit_group_path(entry), :class => "mg-edit-link" do %>
      <span class="icon-stack text-muted">
        <i class="icon-sign-blank icon-stack-base"></i>
        <i class="icon-pencil icon-light"></i>
      </span>
    <% end %>
    <%= link_to group_path(entry), :method => :delete, :class => "mg-delete-link" do %>
      <span class="icon-stack text-danger">
        <i class="icon-sign-blank icon-stack-base"></i>
        <i class="icon-trash icon-light"></i>
      </span>
    <% end %>
    <% end %>
  </td>

  <td> 
    <% display_text, display_class = get_owner_member_details(current_user, entry) %>
    <span class="label label-<%= display_class %>">
      <%= display_text %>
    </span>
  </td>
</tr>

app/views/groups/_group_profile.html.erb
<a href="#" data-toggle="modal" data-target="#modal3" class="pull-center">
  <% if current_user.can?(:invite_friends, @group) %>
  <div class="col-sm-12">
    <div class="col-sm-9">
      <a href="#" data-toggle="modal" data-target="#modal3">
      <button id="email_invite" type="button" class="btn btn-success" style="width: 100%;" >
        <span class="icon-stack">
      <i class="icon icon-circle icon-stack-base" ></i>
        <i class="icon-envelope icon-dark"></i>
      </span>    
      Invite friends to this Group
    </button></a></div>
    <div class="col-sm-3">
      <a href= "/contacts/gmail">
      <button class="btn btn-danger gmail" data-container="body" data-toggle="popover"  data-button="CLOSE" data-placement="top" data-html=true data-content='<button type="button" id="close" class="close"  >&times;</button><i>Import contacts from Gmail'>
        <span class="icon-stack">
      <i class="icon-cloud icon-stack-base"></i><i class="icon-google-plus icon-dark"></i> </span>   From Gmail
    </button></a>
	</div>
	</div>
    <div id = "popover">
		<%= form_for @group, :url => close_popover_groups_path, :html=> {:id =>"popover_form"}, :remote => true do %>
		<% end %>
    </div>
<% end %>
</a>

<div class="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <%= render :partial => "groups/send_invites" %>
</div>
<table class="table table-condensed">
  <thead>
    <tr>
    <th class="col-sm-9 text-center">User</th>
    <th class="col-sm-3 text-center">Status</th>
    </tr>
  </thead>
  <tbody>
    <% @group.users.each do |user| %>
    <tr>
		<td  class="col-sm-9 text-center"> 
      		<%= render_user_image(user,:size => 42,:class_name => "img-circle group-user").html_safe %></td>
     	<td class="col-sm-3 text-center">
        	<span class="badge <%= user.invite_status == 'registered' ? "positive" : "warning" %>" >
              <%= user.translate_status(user.invite_status)%></span></td>
    </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
	jQuery('.group-user').tooltip();
	$(document).click(function(e) {
		if(e.target.id=="close")              
		{
			$('.btn').popover('hide'); 
		}
	})
	$('.btn').on('hidden.bs.popover', function () {
		$("#popover_form").submit();
	})
</script>

app/views/groups/_group_user.html.erb
<div class="mg-group-user">
  <%= fields_for("group[user_attributes][#{group_user.object_id}]", group_user) do |user_form| %>
    <div class="well well-sm remove-left-gutter remove-right-gutter">
      <div class="input-group">
        <%= user_form.text_field :name, {:class => 'text_field form-control', :placeholder => "User Name"} %>
        <span class="input-group-btn">
          <%= link_to("javascript:void(0)", {:onclick => "jQuery(this).parents('.mg-group-user').remove();"}) do %>
            <%= content_tag(:button, content_tag(:i, "", :class => "icon-minus-sign"), {:class => "btn btn-danger", :type =>"button"}.merge(group_user == current_user ? {:disabled => "disabled"}  : {})) %>
          <% end %>
        </span>
      </div><!-- /input-group -->
      <div class="clearfix">
        <%= user_form.text_field :email, {:class => 'text_field form-control', :placeholder => "Email Address"} %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/_groups_entries.html.erb
<% entries.each do |group| %>
  <%= render :partial => "groups/group_entry", :locals => {:entry => group} %>
<% end %>

app/views/groups/_send_invites.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4><span class="help-inline"><i class="icon-user"></i> &nbsp; Invite your friends to this group</span></h4>
    </div>
    <div class="modal-body">
        <%= form_tag({:action => "sendinvites"}, :method => "post", :id => "form_invite") do -%>
        <%= hidden_field_tag :groupid, @group.id, :class => 'text_field' %>
        <%= text_field_tag :emailids, params[:emailids] %>
      <div class="text-center ">
        <br/>
        <button id="send_mail" type="submit" class="btn btn-primary">Send Invites</button>
      </div>
    </div>
        <%end%>
  </div>
</div>

<script type="text/javascript">
  jQuery('#send_mail').click(function () {
    jQuery("#modal3").modal('hide');
  })

  $(document).ready(function() {
    Group.autocomplete("/groups/autocomplete","#emailids","Enter email ids ... ");
  })
</script>

app/views/groups/adduser.html.erb
<%= form_tag :url => group_path(@group), :html => { :class => "edit_group", :id => "edit_group" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <div class="clearfix">
     <%= f.label :users, t("activerecord.attributes.group.name", :default => "Enter Group Code"), :class => :label %>
    <div class="input">
        <%= text_field_tag :users, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
  <button class="btn primary" type="submit">Join This Group</button> or
	<%= link_to "Cancel", groups_path %>
</div>
<% end -%>

app/views/groups/edit.html.erb
<% @page_title = "Edit Group" %>
<%= render :partial => "common/page_title", :locals => {:page_title => @page_title} %>
<%= form_for @group, :validate => true, :url => group_path(@group), :html => { :class => "edit_group mg-group-create-edit", :id => "edit_group" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/groups/index.html.erb
<% @page_title = "Groups" %>
<%= render :partial => "common/page_title", :locals => {:page_title => @page_title} %>

<div id="mg-groups-index">
  <table class="table shadow-row" id="mg-groups-list">
    <tbody id="mg-group-entries">
      <%= render :partial => "groups/groups_entries", :locals => {:entries => @groups} %>
    </tbody>
  </table>
</div>


<%= will_paginate(@groups) %>

app/views/groups/new.html.erb
<%= form_for @group, :validate => true, :url => groups_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/groups/sendinvites.js.erb
 jQuery('.flash-container').replaceWith('<%= escape_javascript(render(:partial => 'common/flashdisplay', :locals => {:flash => flash} ))%>');
 jQuery('#emailids').val('');

app/views/groups/show.html.erb
<% @page_title = "#{@group.name}" %>
<%= render :partial => "common/page_title", :locals => {:page_title => @page_title} %>
<div id="mg-groups-show" class="mg-wrap-container">
  <div class="bs-example bs-example-tabs">
    <ul id="myTab" class="nav nav-tabs lead">
      <li class="active"><a href="#group-balance" data-toggle="tab"><i class="icon-exchange"></i></a></li>
      <li class=""><a href="#profile" data-toggle="tab"><i class="icon-info"></i></a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in" id="group-balance">
        <table class="table table-condensed">
          <thead>
          <tr>
            <th class="col-xs-3">User</th>
            <th class="text-center col-xs-6">Balance</th>
            <th class="text-right col-xs-3"># Expenses</th>
          </tr>
        </thead>
          <tbody>
            <% @balances.each do |balance_entry| %>
              <%= render :partial => "groups/balance_entry", :locals => {:balance_options => balance_entry} %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="tab-pane fade" id="profile">
         <%= render :partial => 'group_profile' %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  jQuery('#myTab a').click(function (e) {
    e.preventDefault();
    jQuery(this).tab('show')
  })

  jQuery(function() {
      var hash = window.location.hash;
      hash == "#profil" && $('ul.nav a[href="#profile"]').tab('show');
      hash == "#profile" && $('ul.nav a[href="' + hash + '"]').tab('show');
      hash == "#profile" && jQuery('#modal3').modal('show');
    });

  <% if Group.find_by_id(params[:id]).popover %> 
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
    jQuery('.btn').popover('show'); 
		})
  <% end %>
</script>