config/routes.rb
Magicaccounts::Application.routes.draw do  
  controller :reports do
    get 'reports' => :index
    get "spend_by_category" => "reports#spend_by_category"
    get "spend_by_account" => "reports#spend_by_account"
    get "spend_by_user" => "reports#spend_by_user"
    get "transaction_count_by_category" => "reports#transaction_count_by_category"
    get "transaction_count_by_account" => "reports#transaction_count_by_account"
    get "avg_spend_by_category" => "reports#avg_spend_by_category"
    get "avg_spend_by_account" => "reports#avg_spend_by_account"
  end

  resources :comments do
    collection do
      get :recent_activities
    end
  end

  root :to => 'users#dashboard'
  match 'groups/:code/adduser' => 'groups#adduser'
  match 'transactions/new/:groupid' => 'transactions#new'
  match 'profile' => "users#dashboard"
  match 'groups/sendinvites' => 'groups#sendinvites'

  controller :sessions do
    get   'login' => :new
    post  'login' => :create
    get   'logout' => :destroy
  end

  resources :groups

  resources :transactions do
    collection do
      get :get_group_balance
      get :autocomplete_category_tags
      get :settle_up
    end
  end

  resources :users do
    collection do
      get :autocomplete_friends
    end

    member do
      get :dashboard
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :initiate_transaction, :only => [:index]

  # GET /transactions
  # GET /transactions.json
  def index
    options = {}
    options[:expense_search_query] = params[:expense_search_query] || ""
    options[:friends] = (params[:friends_list] || "").split(",")
    options[:groups] = (params[:groups_list] || "").split(",")
    options[:start] = params[:start].blank? ? DEFAULT_START_DATE : params[:start] 
    options[:end] = params[:end].blank? ? DEFAULT_END_DATE : params[:end] 
    options[:user_id] = current_user.id
    @transactions = Transaction.search_transactions(options).paginate(:page => (params[:page] || 1), :per_page => 10)
    set_search_params(options)
  end

  def new
    @transaction = Transaction.new
    
    @defaultgroup = @groups.find_by_id(params[:groupid].to_i)
    if @defaultgroup.present? && current_user.can?(:view, @defaultgroup)
      @transaction.group_id = params[:groupid]
      @groupusers = @defaultgroup.users
      @groupusers.each { |user| @transaction.transactions_users.build({:user => User.find_by_id(user.id)})}
    else
      flash[:error] = 'Invalid Group'
    end
  end

  def user_profile
	tu_array = []
	current_user.transactions_users.each do |tu|
		if tu[:amount_paid] > 0
			tu_array << TransactionsUser.joins("JOIN transactions t ON t.id = transaction_id AND t.actors  LIKE '%|#{tu[:user_id]}|%' AND transactions_users.user_id != #{tu[:user_id]} AND transaction_id = #{tu[:transaction_id]} AND transactions_users.amount != amount_paid").map{|x| {:amount => x.amount, :id => x.user_id}}.reduce
		else
			tu_array.push({ :amount => -tu[:amount], :id => Transaction.find(tu[:transaction_id]).user_id})
		end
	end
	grouped = tu_array.compact.group_by{|x| x[:id]}
	keys = grouped.keys
	@summary = keys.map{|k| [k,grouped[k].reduce(0) {|t,h| t+h[:amount]}]}
	@s_left = @summary.select{|s| s[1] > 0}
	@s_right = @summary.select{|s| s[1] < 0}
	@summary = @s_left.length > @s_right.length ? @s_left.zip(@s_right) : @s_right.zip(@s_left)
  end

  def settle_up
    @transaction = Transaction.new
    @transaction.user = current_user
    @transaction.category = "settlement"
    @transaction.transaction_type = 4
    @transaction.remarks = "Payment"

    @defaultgroup = @groups.find_by_id(params[:groupid].to_i)
    if @defaultgroup.present? && current_user.can?(:view, @defaultgroup)
      @transaction.group_id = params[:groupid]
      @groupusers = @defaultgroup.users
      @groupusers.each { |user| @transaction.transactions_users.build({:user => User.find_by_id(user.id)})}
    else
      flash[:error] = 'Invalid Group'
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find_by_id(params[:id])
    authorize! :show, @transaction
    respond_to do |format|
      # Allow the user to see only the transactions that are from his group
      if @groups.find_by_id(@transaction.group.id)
        format.html # show.html.erb
      else
        flash[:error] = "Invalid Expense"
        format.html { redirect_to action: "index" }
      end
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction  = Transaction.find_by_id(params[:id])
    authorize! :change, @transaction
    respond_to do |format|
      if @transaction.present?
        @keywords_query = @transaction.category.split(",").collect(&:strip).collect do |tag|
          {:id => tag, :text => tag, :icon_class => "icon-#{Transaction::CATEGORY_ICON_MAPPING[tag]}"}
        end
        @defaultgroup = @transaction.group
          @groupusers = @transaction.group.users
          (@groupusers - @transaction.transactions_users.collect(&:user)).each do |user|
            @transaction.transactions_users.build({:user => user})
          end
          format.html        
      else
        flash[:error] = "Invalid Expense"
        format.html { redirect_to action: "index" }
      end
    end
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(params[:transaction])

    if @transaction.save
      @comment = @transaction.comments.create( {:activity => " added ", :content => @transaction.remarks, :user_id => current_user.id, :group_id => @transaction.group.id})
      @comment.save
      @transaction.transactions_users.each do |transaction|
        if !(@transaction.user == transaction.user)
          MagicMailer.transaction_notification(@transaction, "Added", transaction.amount, transaction.user).deliver
        end
      end
      flash[:notice] = "Expense was successfully created"
    else
      flash.now[:error] = @transaction.errors.full_messages.compact.uniq.join("<br/>")
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    @transaction = Transaction.find_by_id(params[:id])
    @show_error = false
    authorize! :change, @transaction
    
    if @transaction.present?
      if @transaction.update_attributes(params[:transaction])
        @comment = @transaction.comments.create( {:activity => " changed ", :content => @transaction.remarks, :user_id => current_user.id, :group_id => @transaction.group.id})
        @comment.save!
        flash[:notice] = 'Expense was successfully updated.'
      else
        flash.now[:error] = @transaction.errors.full_messages.compact.uniq.join("<br/>")
      end
    else
      flash.now[:error] = "Expense was not found"
      @show_error = true
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find_by_id(params[:id])
    authorize! :change, @transaction
    if @transaction.present?
      @comment = @transaction.comments.create( {:activity => " removed ", :content => @transaction.remarks, :user_id => current_user.id, :group_id => @transaction.group.id})
      @comment.save
      flash[:notice] = "Transaction was succesfully removed"
      @transaction.destroy
    else
      flash[:error] = "Transaction was not found"
    end

    respond_to do |format|
      format.html { redirect_to profile_path }
    end
  end

  def get_group_balance
    @group = Group.find_by_id(params[:group_id])
    authorize! :view, @group
    @user_group_balance = Transaction.user_balance(@group) if @group.present?
  end

  def autocomplete_category_tags
    entries = Transaction.get_autocomplete_tags(params[:term], params[:page], params[:page_limit], params[:selection])
    @entries_array = entries.collect{|entry| {"icon_class" => "icon-#{Transaction::CATEGORY_ICON_MAPPING[entry]}", "text" => entry.capitalize, "id" => entry }} if entries
    render :inline => @entries_array.to_json
  end

  private
  def initiate_transaction
    @transaction = Transaction.new
    @transaction.user = current_user
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper

  Summary_metadata = {
    "right" => {
              :display_class => "pull-right text-danger col-sm-6",
              :display_string => "You Owe"
    },

    "left" => {
              :display_class => "pull-left text-success col-sm-6",
              :display_string => "Owes You"
    }
  }

  def render_user_transaction_balance(transaction)
    amount = transaction.amount_paid - (transaction.amount || 0)

    if amount < 0
      display_string = "You Pay"
      display_amount = amount.abs.to_s
      display_class = "text-danger"
    elsif amount > 0
      display_string = "You Get"
      display_amount = amount.to_s
      display_class = "text-success"
    else
      display_string = "Settled Up"
      display_class = "text-muted"
      display_amount = amount.to_s
    end
    return content_tag(:div, display_string, :class => display_class) +
    content_tag(:div, display_amount, :class => display_class + " lead")
  end

  def render_user_transaction_balance_detail(transaction)
    amount = transaction.amount_paid - (transaction.amount || 0)

    if amount < 0
      display_string = "Owes #{amount.abs.to_s}"
      display_class = "icon-minus-sign-alt"
      text_class = "text-danger"
    elsif amount > 0
      display_string = "Gets #{amount.to_s}"
      display_class = "icon-plus-sign-alt"
      text_class = "text-success"
    else
      display_string = "Is Settled Up"
      display_class = "icon-smile"
      text_class = "text-success"
    end
    return display_string, display_class, text_class
  end


  def other_user_transactions_exist(current_user)
    current_user.transactions_users.select{|x| x.amount != x.amount_paid}.empty?
  end

  def render_summary_info(entry)
    if entry.present?
		options = entry[1] > 0 ? Summary_metadata["left"] : Summary_metadata["right"]
		return content_tag(:div, User.find(entry[0]).name.titleize + "                     " + options[:display_string] + " " + entry[1].abs.to_s, :class => options[:display_class])
	else
		return content_tag(:div, " " ,:class => "col-sm-6")
	end

  end
end

app/views/transactions/_activityaccounts.html.erb
<ul id ="accact" class="nav nav-list">
  <li class="nav-header clearfix">
    <div class="heading_container">
      <div class ="heading_image">
        <%= image_tag('icons/Account32x32.png', :size => "22x22") %>
      </div>
      <div class="heading_text">
        Accounts
      </div>
    </div>
 </li>
<% if activityaccounts.empty? %>
  <li>There is no activity for this section</li>
<%else%>
<% activityaccounts.each_with_index do |act,index| break if index == limit  %>
  <li>
    <% if act.activity == " added " %>
      <i class="icon-plus-sign"></i>
    <% elsif act.activity == " removed " %>
      <i class="icon-minus-sign"></i>
    <% elsif act.activity == " changed " %>
      <i class="icon-pencil"></i>
    <%end%>
    <strong>
      <%=  User.find_by_id(act.user_id).name %>
    </strong>
    <%= " " + act.activity + " " %>
    <% if Account.find_by_id(act.commentable_id) %> <%= link_to truncate(act.content, :length => 15), :controller => type, :action => 'show', :id => act.commentable_id  %> <% else %> <%= truncate(act.content, :length => 15) %> <% end %>
    <span id="litetext"><%= " " + time_ago_in_words(Time.parse(act.created_at.to_s)) + " ago"    %></span>
  </li>
<% end %>
<% end%>
</ul>

app/views/transactions/_activitytransactions.html.erb
<ul id ="tranact" class="nav nav-list">
<li class="nav-header clearfix">
    <div class="heading_container clearfix">
      <div class ="heading_image">
        <%= image_tag('icons/Transaction32x32.png', :size => "22x22") %>
      </div>
      <div class="heading_text">
        Transactions
      </div>
    </div>
 </li>

</ul>

app/views/transactions/_form.html.erb
<div id="mg-transaction-create">
  <fieldset>
    <div class="input-group">
      <span class="mg-tooltip input-group-addon remove-top-gutter remove-bottom-gutter" data-toggle="tooltip" data-placement="right" data-original-title="Expense Group">
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-group icon-light icon-child"></i>
        </span>
      </span>
      <!-- Green to Red -->
      <div id="mgexpensegroup" class="mg-expense-toggle toggle btn btn-lg btn-success" target-element="#mg-expense-group">
        <input type="checkbox" checked>
        <div class="toggle-group">
          <label class="toggle-on btn btn-lg btn-success"><%= @defaultgroup.name %></label>
        </div>
      </div>
      <a href="javascript:void(0)" class="input-group-addon expense-param-edit remove-top-gutter remove-bottom-gutter" data-toggle="modal" data-target="#mg-expense-group">
        <i class="icon-pencil icon-light icon-child"></i>
      </a>
    </div>

    <div class="input-group">
      <span class="mg-tooltip input-group-addon remove-top-gutter remove-bottom-gutter" data-toggle="tooltip" data-placement="right" title="" data-original-title="Expense Amount">
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-money icon-light icon-child"></i>
        </span>
      </span>
      <%= f.text_field :amount, :value => f.object.amount, :type => 'number', :class => "text-center form-control", :placeholder => "0.00" %>
      <a href="javascript:void(0)" class="input-group-addon expense-param-edit remove-top-gutter remove-bottom-gutter" onclick="jQuery('#transaction_amount').focus();">
        <i class="icon-pencil icon-light icon-child"></i>
      </a>
    </div>

    <div class="input-group">
      <span class="mg-tooltip input-group-addon remove-top-gutter remove-bottom-gutter"  data-toggle="tooltip" data-placement="right" title="" data-original-title="Expense Description">
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-font icon-light icon-child"></i>
        </span>
      </span>
      <%= f.text_area :remarks, :class => 'form-control text-center img-circle', :rows => 2 , :placeholder => "Ex:- Lunch at an indian resturant" %>
      <a href="javascript:void(0)" class="input-group-addon expense-param-edit remove-top-gutter remove-bottom-gutter" onclick="jQuery('#transaction_remarks').focus();">
        <i class="icon-pencil icon-light icon-child"></i>
      </a>
    </div>

    <div class="input-group">
      <span class="mg-tooltip input-group-addon remove-top-gutter remove-bottom-gutter" data-toggle="tooltip" data-placement="right" title="" data-original-title="Expense Date">
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-calendar icon-light icon-child"></i>
        </span>
      </span>
      <!-- Green to Red -->
      <div id="mgexpensedate" class="mg-expense-toggle toggle btn btn-lg btn-success">
        <input type="checkbox" checked>
        <div class="toggle-group">
          <label class="toggle-on btn btn-lg btn-success"><%= (f.object.txndate  || Time.now).strftime("%F") %></label>
        </div>
      </div>
      <a href="javascript:void(0)" class="input-group-addon expense-param-edit remove-top-gutter remove-bottom-gutter" data-toggle="modal" data-target="#mg-expense-date">
        <i class="icon-pencil icon-light icon-child"></i>
      </a>
    </div>

    <div class="input-group">
      <span class="mg-tooltip input-group-addon remove-top-gutter remove-bottom-gutter" data-toggle="tooltip" data-placement="right" title="" data-original-title="Expense Spender">
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-user icon-light icon-child"></i>
        </span>
      </span>
      <!-- Green to Red -->
      <div id ="mgexpensepayer" class="mg-expense-toggle <%= f.object.user_id.present? ? "" : "off" %> toggle btn btn-lg btn-success" data-toggle="toggle" target-element="#mg-expense-payer">
        <input type="checkbox" checked>
        <div class="toggle-group">
          <label class="toggle-on btn btn-lg btn-success"><%= "Paid by #{f.object.user.try(:name)}" %></label>
          <label class="<%= f.object.user_id.present? ? "" : "toggle-off" %> btn btn-lg btn-danger"><strong>Choose Spender</strong></label>
          <span class="toggle-handle btn btn-lg btn-primary"></span>     
        </div>
      </div>
      <a href="javascript:void(0)" class="input-group-addon expense-param-edit remove-top-gutter remove-bottom-gutter"  onclick="Transaction.toggleModalSwitch('#mgexpensepayer');">
        <i class="icon-pencil icon-light icon-child"></i>
      </a>
    </div>

    <div class="input-group">
      <span class="mg-tooltip input-group-addon remove-top-gutter remove-bottom-gutter" data-toggle="tooltip" data-placement="right" title="" data-original-title="Expense Benefactors">
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-sitemap icon-light icon-child"></i>
        </span>
      </span>
      <!-- Green to Red -->
      <% benefactors_amount = f.object.transactions_users.collect(&:amount).compact.sum %>
      <div id="mgexpensebeneficiary" class="mg-expense-toggle toggle <%= benefactors_amount > 0 ? "" : "off" %> btn btn-lg btn-success" data-toggle="toggle"  target-element="#mg-expense-beneficiary" >
        <input type="checkbox" checked>
        <div class="toggle-group">
          <label class="toggle-on btn btn-lg btn-success"><%= Transaction::TRANSACTION_TYPES[f.object.transaction_type || 1] %></label>
          <label class="<%= benefactors_amount > 0 ? '' : 'toggle-off' %> btn btn-lg btn-danger"><strong>Choose Benefactors</strong></label>
          <span class="toggle-handle btn btn-lg btn-primary"></span>     
        </div>
      </div>
      <a href="javascript:void(0)" class="input-group-addon expense-param-edit remove-top-gutter remove-bottom-gutter"  onclick="Transaction.toggleModalSwitch('#mgexpensebeneficiary');">
        <i class="icon-pencil icon-light icon-child"></i>
      </a>
    </div>

    <div class="input-group">
      <span class="mg-tooltip input-group-addon remove-top-gutter remove-bottom-gutter" data-toggle="tooltip" data-placement="right" title="" data-original-title="Expense Categories">
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-tags icon-light icon-child"></i>
        </span>
      </span>
      <!-- Green to Red -->
      <div  id="mgexpensecategories" class="mg-expense-toggle toggle <%= f.object.category.present? ? "" : "off" %> btn btn-lg btn-success" data-toggle="toggle" target-element="#mg-expense-categories">
        <input type="checkbox" checked>
        <div class="toggle-group">
          <label class="toggle-on btn btn-lg btn-success"><%= f.object.category || "Uncategorized" %></i></label>
          <label class="<%= f.object.category.present? ? "" : "toggle-off" %> btn btn-lg btn-default"><strong>Choose Categories</strong></label>
          <span class="toggle-handle btn btn-lg btn-primary"></span>     
        </div>
      </div>
      <a href="javascript:void(0)" class="input-group-addon expense-param-edit remove-top-gutter remove-bottom-gutter"   onclick="Transaction.toggleModalSwitch('#mgexpensecategories');">
        <i class="icon-pencil icon-light icon-child"></i>
      </a>
    </div>
    
    <br/>
    <div class="text-center">
      <%= link_to "Cancel", transactions_path, :class => "btn btn-default" %>
      <%= f.submit "Save", id: "mg-transactions-create-btn", class: "btn btn-primary", disable_with: "Saving..." %>
    </div>
    <%= f.hidden_field :enteredby, :value => (f.object.enteredby || current_user.id.to_s) %>
    <%= f.hidden_field :actors, :value => f.object.actors %>
  </fieldset>
</div>

<%= render :partial => "transactions/modals/expense_date", :locals => {:f => f} %>
<%= render :partial => "transactions/modals/expense_group", :locals => {:f => f} %>
<%= render :partial => "transactions/modals/expense_spender", :locals => {:f => f}  %>
<%= render :partial => "transactions/modals/expense_benefactors", :locals => {:f => f} %>
<%= render :partial => "transactions/modals/expense_categories", :locals => {:f => f} %>

<script type="text/javascript">
  jQuery('.mg-expense-toggle').on('switch-on', this, function(){
    jQuery(jQuery(this).attr('target-element')).modal('show');
  })

  jQuery(document).ready(function(){
    jQuery("#mg-transaction-type li[transaction-type = '<%= f.object.transaction_type || 1 %>']").addClass("active");
    jQuery("#mg-expense-type .transaction_type_<%= f.object.transaction_type || 1 %>").addClass("active in");
  })
</script>

app/views/transactions/_group_balance.html.erb
<% if @groups.present? %>
	<%= select_tag 'balance_group_select', options_for_select(@groups.collect{ |g| [g.name, g.id] }) %>

	<%= render(:partial => 'transactions/group_balance_entries', :locals =>  {:user_group_balance => @user_group_balance})  %>

	<script type="text/javascript">
		jQuery(document).ready(function() { 
			jQuery("#balance_group_select").select2();
			jQuery("#balance_group_select").on("change", function(e) { Transaction.getUserBalance("<%= get_group_balance_transactions_url %>", e.val); });
		});
	</script>
<% else %>
	Please join/create one or more groups
<% end %>

app/views/transactions/_group_balance_entries.html.erb
<div id="balance_group_data">
	<% if user_group_balance.present? %>
		<table class="table table-striped table-bordered account_block">
			<thead>
			  <tr>
			    <th><i class="icon-user"></i> User</th>
			    <th><i class="icon-eye-open"></i> Balance</th>
			  </tr>
			</thead>
			<tbody>
			  <% user_group_balance.each do |balance| %>
			    <% if balance %>
			    <% total_investment = balance.investments.round %>
			    <% total_expenditure = balance.expenditures.round %>
			      <tr>
			        <td><%= balance.user_name == User.find(current_user).name ? content_tag(:b, "Myself") : balance.user_name %></td>
			        <td>
			          <% if total_investment - total_expenditure < 0 %>
			            <span class="balance-label label-important">Rs. <%= total_expenditure - total_investment %></span>
			          <% elsif total_investment - total_expenditure > 0  %>
			            <span class="balance-label label-success">Rs. <%= total_investment - total_expenditure %></span>
			          <% end -%>
			        </td>
			      </tr>
			    <% end %>
			  <% end %>
			</tbody>
		</table>
	<% else %>
		There are no transactions for this group
	<% end %>
</div>

app/views/transactions/_transaction_detail_entry.html.erb
<div class="transaction_detail_entry">
  <div class="well well-sm">
    <h4><i class="icon-quote-left"></i> &nbsp; &nbsp; <span><%= entry.remarks %></span></h4>
  </div>

  <p class="clearfix ">
    <div class="mg-category-tags">
      <div>
        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="icon-tags icon-light icon-child"></i>
        </span><small>&nbsp;</small>
        <% (entry.category || "").split(",").each do |category| %>
        <span class="label label-info">
            <i class="icon-<%= Transaction::CATEGORY_ICON_MAPPING[category.strip] || Transaction::CATEGORY_ICON_MAPPING["general"] %> icon icon-child"></i> &nbsp; <%= category %>
          </span>
        <% end %>
      </div>
      <div>
        <span class="icon-stack">
          <i class="icon-circle icon-stack-base"></i>
          <i class="icon-sitemap icon-light icon-child"></i>
        </span><small>&nbsp;</small>
        <span class="label label-warning">
          <%= entry.group.name %>
        </span>
      </div>
    </div>
  </p>

  <p>
    <ul class="list-group">
      <% entry.transactions_users.each do |tu| %>
        <li class="list-group-item clearfix">
          <div class="col-xs-5 text-center">
            <div class="text-danger">
              <small><i class="icon-minus-sign-alt"></i> &nbsp; <%= tu.amount %></small>
            </div>
            <div class="progress element-reverse">
              <div class="progress-bar progress-bar-danger" width-value="<%= "#{(tu.amount || 0) * 100/entry.amount}%" %>" style= "width: 0%;height: 100%;"></div>
            </div>
          </div>
          
          <div class="col-xs-2 text-center">
            <%= render_user_image(tu.user, :size => 32, :class_name => "img-circle").html_safe %>
          </div>
          
          <div class="col-xs-5 text-center">
            <div class="text-success">
              <small><i class="icon-plus-sign-alt"></i> &nbsp; <%= tu.amount_paid %></small>
            </div>
            <div class="progress">
              <div class="progress-bar progress-bar-success" width-value="<%= "#{tu.amount_paid * 100/entry.amount}%" %>"style="width: 0%; height: 100%;"></div>
            </div>
          </div>

          <div class="col-xs-12 text-center">
            <span class="label label-info"></span>
            <% display_string, display_class, text_class = render_user_transaction_balance_detail(tu) %>
            <h5 class="<%= text_class %>"><%= "#{tu.user.name} #{display_string}" %></h5>
          </div>
        </li>
      <% end %>
    </ul>
  </p>

  <p>
    <%= render_user_image(entry.entered_user, :size => 32, :class_name => "img-circle").html_safe %>
    <span class="text-muted">
      <small> added <%= entry.created_at.strftime("%d %b %Y %H:%m") %></small>
    </span>
    <span class="pull-right">
      <i class="icon-barcode icon-2x"></i><i class="icon-barcode icon-2x"></i>
    </span>
  </p>
</div>

app/views/transactions/_transactions_entries.html.erb
<% entries.each do |transaction| %>
  <%= render :partial => "transactions/transaction_entry", :locals => {:entry => transaction} %>
<% end %>

app/views/transactions/create.js.erb
<% if @transaction.errors.blank? %>
  window.location = '<%= transactions_path %>'
<% else %>
  jQuery('.flash-container').replaceWith('<%= escape_javascript(render(:partial => 'common/flashdisplay', :locals => {:flash => flash} ))%>');
<% end %>

app/views/transactions/get_group_balance.js.erb
jQuery("#balance_group_data").replaceWith("<%= escape_javascript(render(:partial => 'transactions/group_balance_entries', :locals =>  {:user_group_balance => @user_group_balance})) %>");

app/views/transactions/index.html.erb
<% @page_title = "Expenses" %>
<%= render :partial => "common/page_title", :locals => {:page_title => @page_title} %>
<div id="mg-transactions-index">
  <table class="table shadow-row" id="mg-transactions-list">
    <tbody id="mg-transaction-entries">
      <%= render :partial => "transactions/transactions_entries", :locals => {:entries => @transactions} %>
    </tbody>
  </table>
</div>

<div class="text-center">
  <%= will_paginate(@transactions) %>
</div>

app/views/transactions/settle_up.html.erb
<% @page_title = "Settle Up" %>
<%= render :partial => "common/page_title", :locals => {:page_title => @page_title} %>
<div class="clearfix">
  <%= form_for @transaction, :validate => true, :remote => true, :url => transactions_path, :method => :post, :html => { :class => "form form-horizontal" } do |f| -%>
    <%= render :partial => "settle_form", :locals => {:f => f} %>
  <% end -%>
</div>

app/views/transactions/update.js.erb
<% if @transaction.errors.blank? || @show_error %>
  window.location = '<%= transactions_path %>'
<% else %>
  jQuery('.flash-container').replaceWith('<%= escape_javascript(render(:partial => 'common/flashdisplay', :locals => {:flash => flash} ))%>');
<% end %>