config/routes.rb
Magicaccounts::Application.routes.draw do  
  controller :reports do
    get 'reports' => :index
    get "spend_by_category" => "reports#spend_by_category"
    get "spend_by_account" => "reports#spend_by_account"
    get "spend_by_user" => "reports#spend_by_user"
    get "transaction_count_by_category" => "reports#transaction_count_by_category"
    get "transaction_count_by_account" => "reports#transaction_count_by_account"
    get "avg_spend_by_category" => "reports#avg_spend_by_category"
    get "avg_spend_by_account" => "reports#avg_spend_by_account"
  end

  resources :comments do
    collection do
      get :recent_activities
    end
  end

  root :to => 'users#dashboard'
  match 'groups/:code/adduser' => 'groups#adduser'
  match 'transactions/new/:groupid' => 'transactions#new'
  match 'profile' => "users#dashboard"
  match 'groups/sendinvites' => 'groups#sendinvites'

  controller :sessions do
    get   'login' => :new
    post  'login' => :create
    get   'logout' => :destroy
  end

  resources :groups

  resources :transactions do
    collection do
      get :get_group_balance
      get :autocomplete_category_tags
      get :settle_up
    end
  end

  resources :users do
    collection do
      get :autocomplete_friends
    end

    member do
      get :dashboard
    end
  end
end

app/views/common/_common_buttons.html.erb
<div id="mg-app-buttons" class="clearfix">
  <div class="col-xs-3 remove-left-gutter remove-right-gutter">
    <%= link_to(new_group_path, :class => "btn btn-primary btn-sm") do %>
      Group
    <% end %>
  </div>
  <div class="col-xs-3 remove-left-gutter remove-right-gutter">
    <%= link_to(new_transaction_path, :class => "btn btn-danger btn-sm dropdown-toggle", :id =>"mg-add-expense-button", "data-toggle" => "dropdown") do %>
      Expense
    <% end %>
    <ul class="dropdown-menu" role="menu" aria-labelledby="mg-add-expense-button">
      <% current_user.user_groups.each do |group| %>
        <li role="presentation">
          <%= link_to(new_transaction_path(:groupid => group.id), :role => "menuitem", :tabindex=>"-1") do %>
            <% group.name %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-xs-3 remove-left-gutter remove-right-gutter">
    <%= link_to(settle_up_transactions_path, :class => "btn btn-success btn-sm dropdown-toggle", :id =>"mg-settle-expense-button", "data-toggle" => "dropdown") do %>
      Settle Up
    <% end %>
    <ul class="dropdown-menu" role="menu" aria-labelledby="mg-settle-expense-button">
      <% current_user.user_groups.each do |group| %>
        <li role="presentation">
          <%= link_to(settle_up_transactions_path(:groupid => group.id), :role => "menuitem", :tabindex=>"-1") do %>
            <% group.name %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-xs-3 remove-left-gutter remove-right-gutter">
    <%= link_to(recent_activities_comments_path, :class => "btn btn-info btn-sm") do %>
      Activity
    <% end %>
  </div>
</div>

app/views/common/_feature_4_column_static.html.erb
<div class="col-sm-3 panel panel-default">
  <div class="col-sm-12 clearfix h-align-container text-center">
    <div class="h-align">
      <span class="icon-stack icon-2x <%= icon_color %>">
        <i class="icon-circle icon-stack-base"></i>
        <i class="<%= icon_class %> icon-light icon-child"></i>
      </span>
    </div>
    <div class="col-sm-12 h-align">
      <h3><%= feature_title %></h3>
    </div>
    <p class="h-align"><%= feature_content %></p>
  </div>
</div>

app/views/common/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-lg-12">
      <ul class="list-unstyled">
        <li class="pull-right"><a href="#top">Back to top</a></li>
        <li><a href="http://news.bootswatch.com" onclick="pageTracker._link(this.href); return false;">Blog</a></li>
        <li><a href="http://feeds.feedburner.com/bootswatch">RSS</a></li>
        <li><a href="https://twitter.com/thomashpark">Twitter</a></li>
        <li><a href="https://github.com/thomaspark/bootswatch/">GitHub</a></li>
        <li><a href="../help/#api">API</a></li>
        <li><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=F22JEM3Q78JC2">Donate</a></li>
      </ul>
      <p>Made by <a href="http://thomaspark.me">Thomas Park</a>. Contact him at <a href="mailto:hello@thomaspark.me">hello@thomaspark.me</a>.</p>
      <p>Code licensed under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License v2.0</a>.</p>
      <p>Based on <a href="http://getbootstrap.com">Bootstrap</a>. Icons from <a href="http://fortawesome.github.io/Font-Awesome/">Font Awesome</a>. Web fonts from <a href="http://www.google.com/webfonts">Google</a>. Favicon by <a href="https://twitter.com/geraldhiller">Gerald Hiller</a>.</p>
    </div>
  </div>
  
</footer>

app/views/common/_left_side_bar.html.erb
<div id="mg-left-sidebar">
  <ul class="nav nav-pills nav-stacked">
    <li class="<%= active_tab?(params[:action], 'user_profile') ? "active" : "" %>">
      <%= link_to profile_url do %>
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-dashboard icon-<%= active_tab?(params[:action], 'user_profile') ? "dark" : "light" %> icon-child"></i>
        </span>
        <span class="mg-navigation-text">&nbsp; Dashboard</a></span>
      <% end %>
    </li>
    <li class="<%= active_tab?(params[:controller], 'transactions') && params[:action] != 'user_profile' ? "active" : "" %>">
      <%= link_to transactions_path do %>
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-inr icon-<%= active_tab?(params[:controller], 'transactions') && params[:action] != 'user_profile' ? "dark" : "light" %> icon-child"></i>
        </span>
        <span class="mg-navigation-text">&nbsp; Expenses</span>
      <% end %>
    </li>
    <li class="dropdown <%= active_tab?(params[:controller], 'groups') ? "active" : "" %>">
      <%= link_to groups_path do %>
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-sitemap icon-<%= active_tab?(params[:controller], 'groups') ? "dark" : "light" %> icon-child"></i>
        </span>
        <span class="mg-navigation-text">&nbsp; Groups</span>
      <% end %>
    </li>
    <li class="<%= active_tab?(params[:controller], 'tofillup') ? "active" : "" %>">
      <a href="#">
        <span class="icon-stack">
          <i class="icon-sign-blank icon-stack-base"></i>
          <i class="icon-bar-chart icon-light icon-child"></i>
        </span>
        <span class="mg-navigation-text">&nbsp; Reports</span>
      </a>
    </li>
  </ul>
</div>

app/views/common/_logged_in_page.html.erb
<div id="mg-left-pane" class="col-sm-3 hidden-xs">
  <%= render :partial => "common/left_side_bar" %>
</div>
<div id="mg-center-pane" class="col-sm-6">
  <%= render :partial => "common/common_buttons" %>
  <%= render :partial => "common/main_pane" %>
</div>
<div id="mg-right-pane" class="col-sm-3 hidden-xs">
  <%= render :partial => "common/right_side_bar" %>
</div>

app/views/common/_logged_in_tabs.html.erb
<ul class="nav navbar-nav">
  <li class="dropdown">
    <a id="mg-recent-activity" href="#" class="dropdown-toggle" data-toggle="dropdown">
      <button type="button" class="btn btn-info btn-xs"><i class="icon-globe"></i> &nbsp; Activity</button>
    </a>
    <ul class="dropdown-menu panel panel-info panel-sm" id="mg-recent-activity-dropdown">
      <div class="panel-heading">Recent Activity</div>
      <div class="panel-body">
        <%= render :partial => "common/recent_activity" %>
      </div>
      <div class="panel-footer"><button type="button" class="btn btn-info btn-xs">View All Activity</button></div>
    </ul>
  </li>
  <li>
    <a id="mg-add-transaction" href="#">
      <button type="button" class="btn btn-danger btn-xs"><i class="icon-plus-sign"></i> &nbsp; Add Expense</button>
    </a>
  </li>
  <li>
    <a id="mg-settle-transaction" href="#">
      <button type="button" class="btn btn-success btn-xs"><i class="icon-flag-checkered"></i> &nbsp; Settle Expense</button>
    </a>
  </li>
</ul>
<ul class="nav navbar-nav navbar-right pull-right">
  <li>
    <a href="#">
      <%= render_user_image(current_user, 
                            :size => 24, 
                            :class_name => "pull-right img-circle", 
                            :user_name_class => "pull-right mg-user-name") %>
    </a>
  </li>
</ul>

app/views/common/_main_pane.html.erb
<div id="mg-main-pane-container">
  <%= yield %>
</div>

app/views/common/_non_logged_in_tabs.html.erb
<ul class="nav navbar-nav">
  <li class="dropdown">
    <a id="mg-sign-in" href="#" data-toggle="modal" data-target="#modal2" >
       <button type="button" class="btn btn-primary btn-xs"><i class="icon-signin icon"></i> &nbsp; Sign-in</button>
    </a>

  </li>
</ul>

app/views/common/_page_title.html.erb
<div class="well well-sm top-shadow" id= "mg-page-title">
  <h3 class="text-center"><strong><%= page_title || "Welcome !" %></strong></h3>
</div>

app/views/common/_recent_activity.html.erb
<% if @activitytran.empty? %>
  <p>There is no activity for this section<p>
<%else%>
  <% @activitytran.each do |act| %>
    <% activity_transaction = Transaction.find_by_id(act.commentable_id) %>
    <% if activity_transaction.present? %>
        <div class="list-group">
          <a href="<%= transaction_path(activity_transaction) %>" class="list-group-item">
            <h5 class="list-group-item-heading">
              <%= raw(render_user_image(act.user, 
                            :size => 32, :class_name => "img-circle") + render_activity(act)) %> </h5>
            <p class="list-group-item-text">
              <small>
                <%= activity_transaction.remarks %>
              </small>
            </p>
          </a>
        </div>
    <% end %>
  <% end %>
<% end%>

app/views/common/_right_side_bar.html.erb
<% if params[:controller] == "groups" && params[:action] == "show" %>
	<%= render :partial => "groups/group_balance.html.erb" %>
<% else %>

<div id="mg-right-bar">
  <ul id="mg-right-bar-tabs" class="nav nav-tabs">
    <li class="active"><a href="#mg-search-expense" data-toggle="tab"><i class="text-primary icon-search"></i></a></li>
    <li><a href="#mg-overall-balance" data-toggle="tab"><i class="text-primary icon-exchange"></i></a></li>
  </ul>

  <div id="mg-right-bar-content" class="tab-content">
    <%= render :partial => "common/expense_search" %>
    <%= render :partial => "common/user_balance" %>
    <% end %>
  </div>
</div>

app/views/common/_signin_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
      &times;</button>
      <h4 class="modal-title">Login</h4>
    </div>
    <div class="modal-body">

      <%= form_tag({:controller => "sessions", :action => "create", :method => :post }) do %>
        <fieldset>
          <div class="form-group">
            <div class="col-sm-12">
              <div class="input-group input-group-sm">
                <span class="input-group-addon"><i class="icon-envelope"></i></span>
                <%= text_field_tag :inputEmail, "", :placeholder => "Email", :class => "form-control input-sm" %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-12">
              <div class="input-group input-group-sm">
                <span class="input-group-addon"><i class="icon-key"></i></span>
                <%= password_field_tag :inputPassword, "", :placeholder => "Password", :class => "form-control input-sm" %>
              </div>
            </div>
          </div>
          <div class="form-group action-group">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary btn-sm pull-left" id="sign-in-btn">Sign-in</button>
                  <a href="/auth/facebook" data-placement="top" data-toggle="tooltip" data-original-title="Facebook"><i class="icon-facebook-sign icon-2x icon-large"></i></a>
                  <a href= "/auth/google_oauth2" data-placement="top" data-toggle="tooltip" data-original-title="Google"><i class="icon-google-plus-sign icon-2x icon-large"></i></a>
            </div>

                <div class="col-sm-8 pull-left"> <%= link_to("javascript:void", :id => "mg-forgot-password-link", :class => "text-primary"){ raw("Forgot Password ") + content_tag(:i, "", :class=>"icon-question-sign")} %>             </div>

          </div>
        </fieldset>
      <% end %>
  </div>
</div>

app/views/common/_user_balance.html.erb
<div class="tab-pane fade" id="mg-overall-balance">
  <fieldset>
    <legend class="text-center">Balances</legend>
    <div class="text-center text-muted col-lg-4">
      You Owe<br/><h4><span class="lead label label-success"><%= @master_balance[:investments] %></span></h4>
    </div>
    <div class="text-center text-muted col-lg-4">
      You Paid<br/><h4><span class="lead label label-danger"><%= @master_balance[:expenses] %></span></h4>
    </div>
    <div class="text-center text-muted col-lg-4">
      Balance<br/><h4><span class="lead label label-<%= @master_balance[:master_balance] > 0 ? "success" : (@master_balance[:master_balance] < 0 ? "danger" : "default") %>"><%= @master_balance[:master_balance].abs %></span></h4>
    </div>
  </fieldset>
</div>

app/views/common/_user_testimonials.html.erb
<div id="testimonial-carousel" class="carousel slide">
  <div class="carousel-inner">
    <div class="item active">
      <div class="user-testimonial">
        <blockquote>
          <div class="pull-left"><i class="icon-quote-left icon-3x pull-left"></i></div>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
        </blockquote>
      </div>
    </div>
    <div class="item">
      <div class="user-testimonial">
        <blockquote>
          <div class="pull-left"><i class="icon-quote-left icon-3x pull-left"></i></div>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
        </blockquote>
      </div>
    </div>
    <div class="item">
      <div class="user-testimonial">
        <blockquote>
          <div class="pull-left"><i class="icon-quote-left icon-3x pull-left"></i></div>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
          <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
        </blockquote>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  jQuery('.carousel').carousel();
</script>